spring.application.name=demo-park-api
# LOCALE
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

# Postgres database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/demo-park
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Springdoc OpenApi 3.1 Swagger 3
springdoc.swagger-ui.path=/docsPark.html
springdoc.api-docs.path=/docsPark
springdoc.packages-to-scan=com.Bertazz1.demo_park_api.web.controller
